/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aeropuertos.gui;

import com.aeropuertos.dto.Aeropuerto;
import com.aeropuertos.dto.CompaniaAerea;
import com.aeropuertos.dto.VueloBase;
import com.aeropuertos.logica.LogicaNegocio;
import com.aeropuertos.logica.ValidadorDatos;
import com.aeropuertos.modelos.IEscuchador;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author 34675
 */
public class DarAltaVuelosBase extends javax.swing.JDialog {

    /**
     * Creates new form DarAltaVuelosBase
     */
    private DefaultComboBoxModel<Aeropuerto> modeloLista;
    private DefaultComboBoxModel<Aeropuerto> modeloArptoBase;
    private DefaultComboBoxModel<CompaniaAerea> modeloCompania;
    private List<CompaniaAerea> listaCompanias;
    private int longuitud;
    public DarAltaVuelosBase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        longuitud=LogicaNegocio.getListaCompaniasAereas().size();
        modeloLista=new DefaultComboBoxModel<>();
        modeloArptoBase=new DefaultComboBoxModel<>();
        modeloLista.addAll(LogicaNegocio.getListaAeropuetosDestino());
        modeloArptoBase.addElement(LogicaNegocio.getAeropuertoOrigen());
        comboAOrigen.setModel(modeloArptoBase);
        comboADestino.setModel(modeloLista);
        comboADestino.setSelectedIndex(0);
       refrescarListaCompanias();
       
        //lblCodigo.setText(LogicaNegocio.getCompaniaAerea(0).getCodigo());
        spnHSalida.setEditor(new JSpinner.DateEditor(spnHSalida, "HH:mm"));//formato de vista spinner 
        spnHllegada.setEditor(new JSpinner.DateEditor(spnHllegada,"HH:mm"));
        ButtonGroup radioGroup=new ButtonGroup();
        radioGroup.add(rbtnSalida);
        radioGroup.add(rbtnLlegada);
        rbtnSalida.setSelected(true);
        //interfaz que escucha cambios en la lista de compañias para saber cuando se añade una compañia
//        IEscuchador escuchador=new IEscuchador() {
//            @Override
//            public void realizaraCambios() {
//                //refrescarListaCompanias();
//                System.out.println("Lista es de "+LogicaNegocio.getListaCompaniasAereas());
//            }
//        };
//        LogicaNegocio.observable.anaidirEscuchador(escuchador);//se añade el escuchador a la lista de escuchadores
    
    }
    //refresca la etiqueta del codigo de compañia
    private void refrescarDatos(){
        int indice=comboCompania.getSelectedIndex();
        lblCodigo.setText(LogicaNegocio.getCompaniaAerea(indice).getCodigo());
    } 
    private void refrescarListaCompanias(){
        listaCompanias=LogicaNegocio.getListaCompaniasAereas();
        modeloCompania=new DefaultComboBoxModel<>();
        modeloCompania.addAll(listaCompanias);
        comboCompania.setModel(modeloCompania);
        comboCompania.setSelectedIndex(0);
        refrescarDatos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboCompania = new javax.swing.JComboBox<>();
        lblCodigo = new javax.swing.JLabel();
        spnCodigo = new javax.swing.JSpinner();
        comboAOrigen = new javax.swing.JComboBox<>();
        comboADestino = new javax.swing.JComboBox<>();
        spnPlazas = new javax.swing.JSpinner();
        spnHSalida = new javax.swing.JSpinner();
        spnHllegada = new javax.swing.JSpinner();
        txtDOpera = new javax.swing.JTextField();
        rbtnSalida = new javax.swing.JRadioButton();
        rbtnLlegada = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCrearCompania = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Nombre Compañia");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Codigo Vuelo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Aeropuerto Origen");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Aeropuerto Destino");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Nº Plazas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Hora Salida");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Hora Llegada");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Dias Opera");

        comboCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCompaniaActionPerformed(evt);
            }
        });

        lblCodigo.setText("VY");

        spnCodigo.setModel(new javax.swing.SpinnerNumberModel());
        spnCodigo.setMinimumSize(new java.awt.Dimension(75, 22));
        spnCodigo.setPreferredSize(new java.awt.Dimension(75, 22));

        comboAOrigen.setPreferredSize(new java.awt.Dimension(275, 22));

        comboADestino.setPreferredSize(new java.awt.Dimension(275, 22));

        spnPlazas.setModel(new javax.swing.SpinnerNumberModel(100, 100, 200, 1));

        spnHSalida.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spnHSalida.setMinimumSize(new java.awt.Dimension(75, 22));
        spnHSalida.setPreferredSize(new java.awt.Dimension(75, 22));

        spnHllegada.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spnHllegada.setMinimumSize(new java.awt.Dimension(75, 22));
        spnHllegada.setPreferredSize(new java.awt.Dimension(75, 22));

        rbtnSalida.setText("Salida");
        rbtnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSalidaActionPerformed(evt);
            }
        });

        rbtnLlegada.setText("Llegada");
        rbtnLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnLlegadaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Tipo de vuelo");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCrearCompania.setText("...");
        btnCrearCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCompaniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(lblCodigo))
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboADestino, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDOpera, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(spnHllegada, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                        .addComponent(spnHSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(86, 86, 86)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbtnLlegada)
                                .addComponent(rbtnSalida)))
                        .addComponent(spnCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAceptar)
                            .addGap(26, 26, 26)
                            .addComponent(btnCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(comboCompania, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearCompania, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(comboAOrigen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboCompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCompania))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodigo)
                    .addComponent(spnCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboADestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnHSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnSalida))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spnHllegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnLlegada))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDOpera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCompaniaActionPerformed
        refrescarDatos();
        
    }//GEN-LAST:event_comboCompaniaActionPerformed
//refresca los ComboBox con los datos segun el tipo de vuelo,en este caso para vuelo de salida
    private void rbtnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSalidaActionPerformed
        comboAOrigen.setModel(modeloArptoBase);
        comboADestino.setModel(modeloLista);
        comboADestino.setSelectedIndex(0);
       
    }//GEN-LAST:event_rbtnSalidaActionPerformed
       
   //refresca los ComboBox con los datos segun el tipo de vuelo,en este caso para vuelo de llegada 
    private void rbtnLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnLlegadaActionPerformed
        comboAOrigen.setModel(modeloLista);
        comboADestino.setModel(modeloArptoBase);
        comboAOrigen.setSelectedIndex(0);
       
    }//GEN-LAST:event_rbtnLlegadaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String diasOpera=txtDOpera.getText();
        Date hSalida=(Date)spnHSalida.getValue();
        Date hLlegada=(Date)spnHllegada.getValue();
        int nCodigo=(Integer)spnCodigo.getValue();
        int plazas=(Integer)spnPlazas.getValue();
        String dOpera=txtDOpera.getText();
        //se comprueba que todos los datos son correctos
        if (nCodigo<0 || nCodigo>9999){
            JOptionPane.showMessageDialog(this, "Numero entero entre 1 y 9999", "CODIGO VUELO", JOptionPane.ERROR_MESSAGE);
        }
        else if (ValidadorDatos.compararHoras(hLlegada, hSalida)==-1||ValidadorDatos.compararHoras(hLlegada, hSalida)==0 ){
          JOptionPane.showMessageDialog(this, "Hora de salida menor-igual que hora de llegada", "COINCIDENCIA HORAS", JOptionPane.ERROR_MESSAGE);  
        }
        else if (dOpera.isEmpty()){
          JOptionPane.showMessageDialog(this, "Campo vacio", "DIAS OPERA", JOptionPane.ERROR_MESSAGE);  
        }
        else if (!ValidadorDatos.formatoDiasOpera(dOpera, this)){}
        else {
            String codigo=LogicaNegocio.getCompaniaAerea(comboCompania.getSelectedIndex()).getCodigo();
            Aeropuerto origen=(Aeropuerto)comboAOrigen.getSelectedItem();
            Aeropuerto destino=(Aeropuerto)comboADestino.getSelectedItem();
            LocalTime timeSalida=ValidadorDatos.parseDateLocalTimeHora(hSalida);
            LocalTime timeLlegada=ValidadorDatos.parseDateLocalTimeHora(hLlegada);
            VueloBase vueloBase=new VueloBase(codigo+nCodigo, origen, destino, plazas,timeSalida , timeLlegada, diasOpera);
           //se comprueba que no exista un vuelo igual 
            if (LogicaNegocio.anaidirVueloBaseGUI(vueloBase)){
                JOptionPane.showMessageDialog(this, "Se creado el vuelo base"+vueloBase.getCodigo());
                txtDOpera.setText("");
            }
            else  JOptionPane.showMessageDialog(this, "El vuelo ya existe", "COINCIDENCIA VUELO BASE", JOptionPane.ERROR_MESSAGE);  

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCompaniaActionPerformed
        DarAltaCompania altaCompania=new DarAltaCompania(this, true);
        altaCompania.setVisible(true);
    }//GEN-LAST:event_btnCrearCompaniaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    refrescarListaCompanias();
    
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearCompania;
    private javax.swing.JComboBox<Aeropuerto> comboADestino;
    private javax.swing.JComboBox<Aeropuerto> comboAOrigen;
    private javax.swing.JComboBox<CompaniaAerea> comboCompania;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JRadioButton rbtnLlegada;
    private javax.swing.JRadioButton rbtnSalida;
    private javax.swing.JSpinner spnCodigo;
    private javax.swing.JSpinner spnHSalida;
    private javax.swing.JSpinner spnHllegada;
    private javax.swing.JSpinner spnPlazas;
    private javax.swing.JTextField txtDOpera;
    // End of variables declaration//GEN-END:variables
}
