/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aeropuertos.gui;

import com.aeropuertos.dto.VueloDiario;
import com.aeropuertos.logica.LogicaNegocio;
import com.aeropuertos.logica.ValidadorDatos;
import com.aeropuertos.modelos.TablePanelVuelosModel;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author 34675
 */
public class PanelVuelosSalidaLlegada extends javax.swing.JDialog {

    /**
     * Creates new form PanelVuelosSalidaLlegada
     */
    private List<VueloDiario> listaVuelosDiarios;
    private TablePanelVuelosModel modelo;
    private VueloDiario vueloDiario;
    private int filaSeleccionada;
    public PanelVuelosSalidaLlegada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("VUELOS SALIDA/LLEGADA");
        buttonGroup1.add(rdSalida);
        buttonGroup1.add(rdLlegada);
        rdSalida.setSelected(true);
        spnFecha.setEditor(new JSpinner.DateEditor(spnFecha, "dd/MM/yyyy"));
        if (rdSalida.isSelected())establecerTableModel(true);
        else establecerTableModel(false);    
  
    }
    protected VueloDiario getVueloDiarioSeleccionado(){
        return vueloDiario;
    }
    private void establecerTableModel(boolean tipoVuelo){
        listaVuelosDiarios=LogicaNegocio.getVuelosDiariosFecha((Date)spnFecha.getValue(), tipoVuelo);
        if(listaVuelosDiarios!=null){
            modelo=new TablePanelVuelosModel(listaVuelosDiarios,LogicaNegocio.getListaActualVuelosBase()
                    , tipoVuelo);
            tabla.setModel(modelo);
        }else{
            JOptionPane.showMessageDialog(this, "No se muestran vuelos con fechas anteriores a la actual");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdSalida = new javax.swing.JRadioButton();
        rdLlegada = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnTemperaturas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        rdSalida.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rdSalida.setText("Salida");
        rdSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSalidaActionPerformed(evt);
            }
        });

        rdLlegada.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rdLlegada.setText("Llegada");
        rdLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLlegadaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Tipo deVuelo");

        spnFecha.setModel(new javax.swing.SpinnerDateModel());
        spnFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spnFecha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnFechaStateChanged(evt);
            }
        });

        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnTemperaturas.setText("Temperaturas");
        btnTemperaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperaturasActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdSalida)
                            .addComponent(rdLlegada))
                        .addComponent(jLabel1))
                    .addComponent(btnTemperaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdSalida)
                        .addGap(18, 18, 18)
                        .addComponent(rdLlegada)
                        .addGap(18, 18, 18)
                        .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTemperaturas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSalidaActionPerformed
        establecerTableModel(true);

    }//GEN-LAST:event_rdSalidaActionPerformed

    private void rdLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLlegadaActionPerformed
        establecerTableModel(false);

    }//GEN-LAST:event_rdLlegadaActionPerformed

    private void spnFechaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnFechaStateChanged
       if(rdSalida.isSelected())establecerTableModel(true);
       else establecerTableModel(false);
 
    }//GEN-LAST:event_spnFechaStateChanged

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
         filaSeleccionada=tabla.getSelectedRow();
        vueloDiario=listaVuelosDiarios.get(filaSeleccionada);
     
    }//GEN-LAST:event_tablaMouseClicked

    private void btnTemperaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperaturasActionPerformed
         //si la fecha no es la actual entonces no permite ver las temperaturas
        int fechaCorrecta=ValidadorDatos.compararFechaActual((Date)spnFecha.getValue());
        if(fechaCorrecta!=0){
            JOptionPane.showMessageDialog(this, "Solo se muestran temperqaturas del dia actual");
            vueloDiario=null;
        }else{
            if(vueloDiario==null){
                JOptionPane.showMessageDialog(this, "No ha seleccionado vuelo");
            }else{
               PanelVuelosTemperaturas temperaturas=new PanelVuelosTemperaturas(this, true);
               temperaturas.setVisible(true);
            } 
        }
    }//GEN-LAST:event_btnTemperaturasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTemperaturas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdLlegada;
    private javax.swing.JRadioButton rdSalida;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
