/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aeropuertos.gui;

import com.aeropuertos.componentes.DtoEditorApiRestFull;
import com.aeropuertos.dto.VueloBase;
import com.aeropuertos.dto.VueloDiario;
import com.aeropuertos.logica.LogicaNegocio;

/**
 *
 * @author 34675
 */
public class PanelVuelosTemperaturas extends javax.swing.JDialog {

    /**
     * Creates new form PanelVuelosTemperaturas
     */
    private String  apiKey;
    private PanelVuelosSalidaLlegada panel;
    private VueloDiario vueloDiario;
    public PanelVuelosTemperaturas(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        panel=(PanelVuelosSalidaLlegada)parent; 
        vueloDiario=panel.getVueloDiarioSeleccionado();
        apiKey=LogicaNegocio.getApiKey();
        VueloBase vueloBase=LogicaNegocio.getVueloBaseListaActual(vueloDiario.getCodigo());
        lblOrigen.setText(vueloBase.getOrigen().getNombre());
        lblDestino.setText(vueloBase.getDestino().getNombre());
        String municipioOrigen=vueloBase.getOrigen().getMunicipio();
        String municipioDestino=vueloBase.getDestino().getMunicipio();
        tablaOrigen.setTableModel(new DtoEditorApiRestFull(municipioOrigen, apiKey));
        tablaDestino.setTableModel(new DtoEditorApiRestFull(municipioDestino,apiKey));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        tablaOrigen = new com.aeropuertos.componentes.JPanelApirestFull();
        jLabel3 = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        tablaDestino = new com.aeropuertos.componentes.JPanelApirestFull();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ORIGEN");

        lblOrigen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(255, 0, 0));
        lblOrigen.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DESTINO");

        lblDestino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDestino.setForeground(new java.awt.Color(255, 0, 0));
        lblDestino.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tablaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tablaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblOrigen;
    private com.aeropuertos.componentes.JPanelApirestFull tablaDestino;
    private com.aeropuertos.componentes.JPanelApirestFull tablaOrigen;
    // End of variables declaration//GEN-END:variables
}
