package com.aeropuertos.gui;

import com.aeropuertos.dto.Aeropuerto;
import com.aeropuertos.logica.LogicaNegocio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 34675
 */
public class PantallaPrincipal extends javax.swing.JFrame {

   private Aeropuerto aeropuertoBase;
   private List<Aeropuerto> listaAeropuertoNobase=new ArrayList<>();
    public PantallaPrincipal() {
        initComponents();
        DefaultComboBoxModel<Aeropuerto> modelo=new DefaultComboBoxModel<Aeropuerto>();
        modelo.addAll(LogicaNegocio.getListaAeropuertos());
        comboBoxAeropuertos.setModel(modelo);
        comboBoxAeropuertos.setSelectedIndex(1);
        mnuCompania.setEnabled(false);
        mnuVuelosBase.setEnabled(false);
        mnuVuelosDiarios.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxAeropuertos = new javax.swing.JComboBox<>();
        btnSeleccionar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCompania = new javax.swing.JMenu();
        mnuCrearCmp = new javax.swing.JMenuItem();
        mnuEliminarCmp = new javax.swing.JMenuItem();
        mnuModificarCmp = new javax.swing.JMenuItem();
        mnuConsultarCmp = new javax.swing.JMenuItem();
        mnuVuelosBase = new javax.swing.JMenu();
        mnuCrearVuelo = new javax.swing.JMenuItem();
        mnuEliminarVuelo = new javax.swing.JMenuItem();
        mnuModificarVuelo = new javax.swing.JMenuItem();
        mnuConsultarVuelo = new javax.swing.JMenuItem();
        mnuVuelosDiarios = new javax.swing.JMenu();
        mnuAltaVueloDiario = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        comboBoxAeropuertos.setToolTipText("");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        mnuCompania.setText("Compañias");

        mnuCrearCmp.setText("Crear");
        mnuCrearCmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearCmpActionPerformed(evt);
            }
        });
        mnuCompania.add(mnuCrearCmp);

        mnuEliminarCmp.setText("Eliminar");
        mnuEliminarCmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarCmpActionPerformed(evt);
            }
        });
        mnuCompania.add(mnuEliminarCmp);

        mnuModificarCmp.setText("Modificar");
        mnuModificarCmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarCmpActionPerformed(evt);
            }
        });
        mnuCompania.add(mnuModificarCmp);

        mnuConsultarCmp.setText("Consultar");
        mnuConsultarCmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarCmpActionPerformed(evt);
            }
        });
        mnuCompania.add(mnuConsultarCmp);

        jMenuBar1.add(mnuCompania);

        mnuVuelosBase.setText("Vuelo Base");

        mnuCrearVuelo.setText("Cear");
        mnuCrearVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearVueloActionPerformed(evt);
            }
        });
        mnuVuelosBase.add(mnuCrearVuelo);

        mnuEliminarVuelo.setText("Eliminar");
        mnuEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarVueloActionPerformed(evt);
            }
        });
        mnuVuelosBase.add(mnuEliminarVuelo);

        mnuModificarVuelo.setText("Modificar");
        mnuModificarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarVueloActionPerformed(evt);
            }
        });
        mnuVuelosBase.add(mnuModificarVuelo);

        mnuConsultarVuelo.setText("Consultar");
        mnuConsultarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarVueloActionPerformed(evt);
            }
        });
        mnuVuelosBase.add(mnuConsultarVuelo);

        jMenuBar1.add(mnuVuelosBase);

        mnuVuelosDiarios.setText("Vuelos Diarios");

        mnuAltaVueloDiario.setText("Crear");
        mnuAltaVueloDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaVueloDiarioActionPerformed(evt);
            }
        });
        mnuVuelosDiarios.add(mnuAltaVueloDiario);

        mnuEliminar.setText("Eliminar");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        mnuVuelosDiarios.add(mnuEliminar);

        jMenuBar1.add(mnuVuelosDiarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(btnSeleccionar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCrearCmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearCmpActionPerformed
 //crear un dialogo de insertar compañias
      DarAltaCompania darAltaCompania=new DarAltaCompania(new JDialog(), true);
      darAltaCompania.setVisible(true);
    }//GEN-LAST:event_mnuCrearCmpActionPerformed

    private void mnuModificarCmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarCmpActionPerformed
      ModificarCompaniaAerea modificar=new ModificarCompaniaAerea(this, true);
      modificar.setVisible(true);
    }//GEN-LAST:event_mnuModificarCmpActionPerformed

    private void mnuConsultarCmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarCmpActionPerformed
      ConsultarCompaniasAereas consultarCompaniasAereas=new ConsultarCompaniasAereas(this, true);
      consultarCompaniasAereas.setVisible(true);
    }//GEN-LAST:event_mnuConsultarCmpActionPerformed

    private void mnuCrearVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearVueloActionPerformed
     DarAltaVuelosBase darAltaVuelosBase=new DarAltaVuelosBase(this, true);
     darAltaVuelosBase.setVisible(true);
    }//GEN-LAST:event_mnuCrearVueloActionPerformed

    private void mnuConsultarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarVueloActionPerformed
      ConsultarVuelosBase vuelosBase=new ConsultarVuelosBase(this, true);
      vuelosBase.setVisible(true);
    }//GEN-LAST:event_mnuConsultarVueloActionPerformed

    private void mnuEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarVueloActionPerformed
   DarBajaVueloBase bajaVueloBase=new DarBajaVueloBase(this, true);
   bajaVueloBase.setVisible(true);
    }//GEN-LAST:event_mnuEliminarVueloActionPerformed

    private void mnuEliminarCmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarCmpActionPerformed
       DarBajaCompania darBajaCompania=new DarBajaCompania(this, true);
       darBajaCompania.setVisible(true);
    }//GEN-LAST:event_mnuEliminarCmpActionPerformed

    private void mnuModificarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarVueloActionPerformed

    }//GEN-LAST:event_mnuModificarVueloActionPerformed

    private void mnuAltaVueloDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaVueloDiarioActionPerformed

    }//GEN-LAST:event_mnuAltaVueloDiarioActionPerformed

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed

    }//GEN-LAST:event_mnuEliminarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
       //recupero el aeropuerto seleccionado
        aeropuertoBase=(Aeropuerto)comboBoxAeropuertos.getSelectedItem();
        //pregunta si el aeropuerto elegigo es el correcto
        int opcion=JOptionPane.showConfirmDialog(this,("Su aeropuerto base sera "+aeropuertoBase.getNombre()),
                "AEROPUERTO BASE", JOptionPane.YES_NO_OPTION);
        if (opcion==0){
            LogicaNegocio.setAeropuertoBase(aeropuertoBase);
            listaAeropuertoNobase=LogicaNegocio.getListaAeropuetosBis();
            comboBoxAeropuertos.setVisible(false);
            comboBoxAeropuertos.setEditable(false);
            btnSeleccionar.setVisible(false);
            btnSeleccionar.setEnabled(false);
            mnuCompania.setEnabled(true);
            mnuVuelosBase.setEnabled(true);
            mnuVuelosDiarios.setEnabled(true);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Lista final compañias:"+LogicaNegocio.getListaCompaniasAereas().size());
        System.out.println("Lista final vuelos base:"+LogicaNegocio.getListaVueloBase().size());
        System.out.println("Lista final vuelos diarios:"+LogicaNegocio.getListaVuelosDIarios().size());
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<Aeropuerto> comboBoxAeropuertos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAltaVueloDiario;
    private javax.swing.JMenu mnuCompania;
    private javax.swing.JMenuItem mnuConsultarCmp;
    private javax.swing.JMenuItem mnuConsultarVuelo;
    private javax.swing.JMenuItem mnuCrearCmp;
    private javax.swing.JMenuItem mnuCrearVuelo;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuEliminarCmp;
    private javax.swing.JMenuItem mnuEliminarVuelo;
    private javax.swing.JMenuItem mnuModificarCmp;
    private javax.swing.JMenuItem mnuModificarVuelo;
    private javax.swing.JMenu mnuVuelosBase;
    private javax.swing.JMenu mnuVuelosDiarios;
    // End of variables declaration//GEN-END:variables
}
