/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aeropuertos.componentes;

import com.aeropuertos.dto.Aeropuerto;
import com.aeropuertos.logica.LogicaNegocio;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author 34675
 */
public class JpanelConsultarTemperaturas extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form JpanelConsultarTemperaturas
     */
    private DtoEditorApiRestFull dtoEditor;
    private Aeropuerto aeropuerto;
    private String apikey=LogicaNegocio.getApiKey();
    private List<Aeropuerto> listaAeropuertos;
    DefaultComboBoxModel<Aeropuerto> modelo;
    public JpanelConsultarTemperaturas() {
        initComponents();
        listaAeropuertos=new ArrayList<>();
        
        listaAeropuertos.add(new Aeropuerto("BIO", "Aeropuerto Bilbao", "48020"));
        listaAeropuertos.add(new Aeropuerto("BCN", "Aeropuerto Josep Tarradellas Barcelona-El Prat", "08019"));
        listaAeropuertos.add(new Aeropuerto("AGP", "Aeropuerto de Málaga-Costa del Sol", "29067"));
        listaAeropuertos.add(new Aeropuerto("GRX", "Aeropuerto Federico García Lorca Granada-Jaén", "18059"));
        listaAeropuertos.add(new Aeropuerto("MAD", "Aeropuerto Adolfo Suárez Madrid-Barajas", "28079"));
        listaAeropuertos.add(new Aeropuerto("TFN", "Aeropuerto de Tenerife Norte-Ciudad de La Laguna", "38023"));
        listaAeropuertos.add(new Aeropuerto("TFS", "Aeropuerto de Tenerife Sur", "38017"));
        listaAeropuertos.add(new Aeropuerto("ZAZ", "Aeropuerto de Zaragoza", "50297"));
        modelo = new DefaultComboBoxModel<>();
        modelo.addAll(listaAeropuertos);
        comboAeropuertos.setModel(modelo);
        comboAeropuertos.setSelectedIndex(0);
        
        
        
        
        
    }
    public void refrescarDatos(){
        aeropuerto=(Aeropuerto)comboAeropuertos.getSelectedItem();
        dtoEditor=new DtoEditorApiRestFull(aeropuerto.getMunicipio(), apikey);
        tablaTemperaturas.setTableModel(dtoEditor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboAeropuertos = new javax.swing.JComboBox<>();
        tablaTemperaturas = new com.aeropuertos.componentes.JPanelApirestFull();

        comboAeropuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAeropuertosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablaTemperaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tablaTemperaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboAeropuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAeropuertosActionPerformed
      refrescarDatos();

        // TODO add your handling code here:
    }//GEN-LAST:event_comboAeropuertosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Aeropuerto> comboAeropuertos;
    private com.aeropuertos.componentes.JPanelApirestFull tablaTemperaturas;
    // End of variables declaration//GEN-END:variables
}
