/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aeropuertos.componentes;

import java.io.Serializable;

/**
 *
 * @author 34675
 */
public class JPanelApirestFull extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form JPanelApirestFull
     */
    private TablaApirestFullModel modelo;
    private DtoEditorApiRestFull dtoEditor;
    public JPanelApirestFull() {
        initComponents();
        
        
    }

    public DtoEditorApiRestFull getDtoEditor() {
        return dtoEditor;
    }

    public void setDtoEditor(DtoEditorApiRestFull dtoEditor) {
        this.dtoEditor = dtoEditor;
        if(dtoEditor!=null){
         modelo=new TablaApirestFullModel(dtoEditor);
         tabla.setModel(modelo);
         
        }
        
    }
    public void setTableModel(DtoEditorApiRestFull dtoEditor){
        if (dtoEditor!=null){
       modelo=new TablaApirestFullModel(dtoEditor);
       tabla.setModel(modelo);
      } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
