/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aeropuertos.componentes;

import java.io.Serializable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 34675
 */
public class MostrarDatosPanel extends javax.swing.JPanel implements Serializable {

   private Object[][] filas;
   private String[] columnames;
  
  
    public MostrarDatosPanel() {
        initComponents();
        refrescarDatosTabla();
    }

    public Object[][] getFilas() {
        return filas;
    }

    public void setFilas(Object[][] filas) {
        this.filas = filas;
    }

    public String[] getColumnames() {
        return columnames;
    }

    public void setColumnames(String[] columnames) {
        this.columnames = columnames;
    }
   private void refrescarDatosTabla(){
       DefaultTableModel modelo=new DefaultTableModel(filas, columnames);
       tabla.setModel(modelo); 
   }
    public void setdatos(Object[][]rows,String[]columns)  {
        if (filas!=null & columnames!=null & rows[0].length==columns.length){
            this.filas=rows;
            this.columnames=columns;
        }
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
